# workflow 의 이름
name : Deploy To EC2

# event : 실행 되는 시점을 설정
on :
  push :
    branches :
      - main

# 1개의 workflow 는 1개 이상의 Job 으로 구성 된다.
# 여러 Job 은 기본적으로 병렬 수행 된다.
jobs :
  # Job 을 식별하기 위한 id
  Deploy:
    # 로직을 실행 시킬수 있는 컴퓨터
    runs-on: ubuntu-latest

    # 특정 작업을 수행하는 가장 작은 단위
    # Job 은 여러 step 으로 구성되어 있다.
    steps:
      - name: SSH(원격 접속)로 EC2 에 접속하기
        uses: appleboy/ssh-action@v.1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/ubuntu/github-actions
            git pull origin main
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &